import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

const TASK_STATUSES = ["NOT_STARTED", "IN_PROGRESS", "DATA_AWAITED", "UNDER_REVIEW", "FILED_DONE", "ON_HOLD"] as const
const TASK_PRIORITIES = ["LOW", "MEDIUM", "HIGH", "URGENT"] as const
const SERVICE_TYPES = ["GST_RETURN", "TDS", "COMPANY_LAW", "BOOKKEEPING", "AUDIT", "INCOME_TAX", "OTHER"] as const

const TASK_TITLES = [
  "Prepare GSTR-1 for Q1",
  "File TDS return for March",
  "Review annual compliance report",
  "Update client financial statements",
  "Conduct internal audit",
  "Prepare income tax return",
  "Review balance sheet",
  "Update payroll records",
  "Prepare GST reconciliation",
  "File ROC annual return",
  "Review client invoices",
  "Update fixed asset register",
  "Prepare quarterly financial report",
  "Review expense claims",
  "Update tax depreciation schedule",
  "Prepare bank reconciliation",
  "Review client contracts",
  "Update VAT records",
  "Prepare statutory audit report",
  "Review client ledger",
  "Update inventory records",
  "Prepare GST annual return",
  "Review client tax filings",
  "Update accounts payable",
  "Prepare monthly financial summary",
  "Review client compliance status",
  "Update accounts receivable",
  "Prepare tax planning report",
  "Review client GST filings",
  "Update profit and loss statement",
  "Prepare cash flow statement",
  "Review client TDS certificates",
  "Update tax registers",
  "Prepare investment summary",
  "Review client bank statements",
  "Update loan records",
  "Prepare budget variance report",
  "Review client expenses",
  "Update depreciation schedule",
  "Prepare GST audit report",
  "Review client income tax filings",
  "Update statutory registers",
  "Prepare compliance checklist",
  "Review client ROC filings",
  "Update client master data",
  "Prepare monthly tax summary",
  "Review client service tax filings",
  "Update tax computation sheets",
  "Prepare year-end tax planning",
  "Review client audit reports",
  "Update client communication log",
  "Prepare quarterly GST report",
  "Review client financial ratios",
  "Update client risk assessment",
  "Prepare tax advisory report",
  "Review client compliance calendar",
  "Update client document checklist",
  "Prepare GST refund application",
  "Review client tax notices",
  "Update client filing status",
  "Prepare TDS certificate request",
  "Review client payment schedules",
  "Update client service agreements",
  "Prepare client onboarding checklist",
  "Review client KYC documents",
  "Update client engagement letters",
  "Prepare client billing summary",
  "Review client outstanding invoices",
  "Update client payment tracking",
  "Prepare client performance report",
  "Review client service delivery",
  "Update client satisfaction metrics",
  "Prepare client retention plan",
  "Review client feedback",
  "Update client communication plan",
  "Prepare client annual review",
  "Review client growth metrics",
  "Update client service portfolio",
  "Prepare client cross-sell plan",
  "Review client referral program",
  "Update client loyalty program",
  "Prepare client training material",
  "Review client support tickets",
  "Update client knowledge base",
  "Prepare client FAQ documentation",
  "Review client usage analytics",
  "Update client onboarding process",
  "Prepare client exit survey",
  "Review client churn analysis",
  "Update client retention strategies",
  "Prepare client success plan",
  "Review client health score",
  "Update client engagement metrics",
  "Prepare client quarterly review",
  "Review client annual performance",
  "Update client service level agreement",
  "Prepare client renewal proposal",
  "Review client contract terms",
  "Update client pricing strategy",
  "Prepare client value proposition",
  "Review client competitive analysis",
  "Update client market positioning",
  "Prepare client growth strategy",
  "Review client expansion plans",
  "Update client partnership opportunities",
  "Prepare client integration plan",
  "Review client system requirements",
  "Update client technical documentation",
  "Prepare client implementation guide",
  "Review client training schedule",
  "Update client support procedures",
  "Prepare client escalation matrix",
  "Review client service catalog",
  "Update client service roadmap",
  "Prepare client feature requests",
  "Review client enhancement suggestions",
  "Update client bug reports",
  "Prepare client maintenance schedule",
  "Review client system uptime",
  "Update client performance metrics",
  "Prepare client capacity planning",
  "Review client scalability options",
  "Update client disaster recovery plan",
  "Prepare client security audit",
  "Review client compliance requirements",
  "Update client data privacy policy",
  "Prepare client GDPR assessment",
  "Review client data governance",
  "Update client data classification",
  "Prepare client data retention policy",
  "Review client data backup strategy",
  "Update client data migration plan",
  "Prepare client system integration",
  "Review client API documentation",
  "Update client webhooks configuration",
  "Prepare client custom development",
  "Review client third-party integrations",
  "Update client plugin architecture",
  "Prepare client extension development",
  "Review client mobile app requirements",
  "Update client responsive design",
  "Prepare client accessibility audit",
  "Review client SEO optimization",
  "Update client content strategy",
  "Prepare client social media plan",
  "Review client email marketing",
  "Update client analytics setup",
  "Prepare client conversion optimization",
  "Review client A/B testing",
  "Update client personalization strategy",
  "Prepare client customer journey map",
  "Review client touchpoint analysis",
  "Update client omnichannel strategy",
  "Prepare client loyalty program",
  "Review client gamification",
  "Update client referral system",
  "Prepare client community building",
  "Review client user-generated content",
  "Update client influencer marketing",
  "Prepare client partnership marketing",
  "Review client event marketing",
  "Update client PR strategy",
  "Prepare client crisis communication",
  "Review client brand guidelines",
  "Update client visual identity",
  "Prepare client brand positioning",
  "Review client messaging framework",
  "Update client tone of voice",
  "Prepare client content calendar",
  "Review client editorial guidelines",
  "Update client social media policy",
  "Prepare client crisis management",
  "Review client reputation management",
  "Update client online monitoring",
  "Prepare client sentiment analysis",
  "Review client competitive intelligence",
  "Update client market research",
  "Prepare client customer insights",
  "Review client persona development",
  "Update client segmentation strategy",
  "Prepare client targeting strategy",
  "Review client positioning statement",
  "Update client value proposition",
  "Prepare client messaging hierarchy",
  "Review client creative brief",
  "Update client campaign strategy",
  "Prepare client media plan",
  "Review client budget allocation",
  "Update client ROI measurement",
  "Prepare client performance dashboard",
  "Review client KPI framework",
  "Update client analytics implementation",
  "Prepare client data visualization",
  "Review client reporting automation",
  "Update client insight generation",
  "Prepare client predictive analytics",
  "Review client machine learning",
  "Update client AI implementation",
  "Prepare client automation strategy",
  "Review client process optimization",
  "Update client workflow automation",
  "Prepare client RPA implementation",
  "Review client digital transformation",
  "Update client change management",
  "Prepare client training program",
  "Review client adoption strategy",
  "Update client user adoption",
  "Prepare client success metrics",
  "Review client impact assessment",
  "Update client ROI calculation",
  "Prepare client business case",
  "Review client investment analysis",
  "Update client financial modeling",
  "Prepare client scenario planning",
  "Review client risk assessment",
  "Update client mitigation strategy",
  "Prepare client contingency plan",
  "Review client business continuity",
  "Update client disaster recovery",
  "Prepare client security audit",
  "Review client penetration testing",
  "Update client vulnerability assessment",
  "Prepare client compliance audit",
  "Review client regulatory compliance",
  "Update client legal review",
  "Prepare client contract review",
  "Review client IP protection",
  "Update client trademark registration",
  "Prepare client patent filing",
  "Review client copyright registration",
  "Update client trade secret protection",
  "Prepare client data protection",
  "Review client privacy policy",
  "Update client cookie policy",
  "Prepare client terms of service",
  "Review client privacy notice",
  "Update client consent management",
  "Prepare client data subject rights",
  "Review client data breach response",
  "Update client incident response",
  "Prepare client security awareness",
  "Review client phishing simulation",
  "Update client security training",
  "Prepare client security policy",
  "Review client access control",
  "Update client identity management",
  "Prepare client authentication strategy",
  "Review client authorization framework",
  "Update client session management",
  "Prepare client encryption strategy",
  "Review client key management",
  "Update client secure coding",
  "Prepare client code review",
  "Review client security testing",
  "Update client vulnerability scanning",
  "Prepare client threat modeling",
  "Review client security monitoring",
  "Update client incident response",
  "Prepare client forensic analysis",
  "Review client malware detection",
  "Update client endpoint protection",
  "Prepare client network security",
  "Review client firewall configuration",
  "Update client intrusion detection",
  "Prepare client security analytics",
  "Review client SIEM implementation",
  "Update client log management",
  "Prepare client security reporting",
  "Review client compliance reporting",
  "Update client audit trail",
  "Prepare client security governance",
  "Review client risk management",
  "Update client security architecture",
  "Prepare client security roadmap",
  "Review client security budget",
  "Update client security staffing",
  "Prepare client security outsourcing",
  "Review client security vendor management",
  "Update client security SLA",
  "Prepare client security metrics",
  "Review client security KPIs",
  "Update client security dashboard",
  "Prepare client security reporting",
  "Review client security communication",
  "Update client security awareness",
  "Prepare client security culture",
  "Review client security leadership",
  "Update client security strategy",
  "Prepare client security vision",
  "Review client security mission",
  "Update client security values",
  "Prepare client security principles",
  "Review client security standards",
  "Update client security frameworks",
  "Prepare client security best practices",
  "Review client security guidelines",
  "Update client security procedures",
  "Prepare client security processes",
  "Review client security controls",
  "Update client security measures",
  "Prepare client security safeguards",
  "Review client security countermeasures",
  "Update client security defenses",
  "Prepare client security barriers",
  "Review client security protections",
  "Update client security shields",
  "Prepare client security layers",
  "Review client security depth",
  "Update client security breadth",
  "Prepare client security coverage",
  "Review client security scope",
  "Update client security boundaries",
  "Prepare client security perimeter",
  "Review client security zones",
  "Update client security segments",
  "Prepare client security compartments",
  "Review client security domains",
  "Update client security realms",
  "Prepare client security territories",
  "Review client security regions",
  "Update client security areas",
  "Prepare client security spaces",
  "Review client security environments",
  "Update client security contexts",
  "Prepare client security scenarios",
  "Review client security use cases",
  "Update client security requirements",
  "Prepare client security specifications",
  "Review client security designs",
  "Update client security implementations",
  "Prepare client security deployments",
  "Review client security operations",
  "Update client security maintenance",
  "Prepare client security support",
  "Review client security services",
  "Update client security solutions",
  "Prepare client security products",
  "Review client security tools",
  "Update client security technologies",
  "Prepare client security platforms",
  "Review client security infrastructure",
  "Update client security architecture",
  "Prepare client security systems",
  "Review client security applications",
  "Update client security software",
  "Prepare client security hardware",
  "Review client security networks",
  "Update client security data",
  "Prepare client security information",
  "Review client security knowledge",
  "Update client security wisdom",
  "Prepare client security intelligence",
  "Review client security insight",
  "Update client security understanding",
  "Prepare client security awareness",
  "Review client security consciousness",
  "Update client security mindfulness",
  "Prepare client security vigilance",
  "Review client security alertness",
  "Update client security readiness",
  "Prepare client security preparedness",
  "Review client security responsiveness",
  "Update client security resilience",
  "Prepare client security adaptability",
  "Review client security flexibility",
  "Update client security agility",
  "Prepare client security speed",
  "Review client security efficiency",
  "Update client security effectiveness",
  "Prepare client security excellence",
  "Review client security quality",
  "Update client security reliability",
  "Update client security availability",
  "Update client security integrity",
  "Update client security confidentiality",
  "Update client security authenticity",
  "Update client security non-repudiation",
  "Update client security accountability",
  "Update client security auditability",
  "Update client security traceability",
  "Update client security transparency",
  "Update client security visibility",
  "Update client security observability",
  "Update client security measurability",
  "Update client security testability",
  "Update client security maintainability",
  "Update client security scalability",
  "Update client security interoperability",
  "Update client security portability",
  "Update client security usability",
  "Update client security accessibility",
  "Update client security inclusivity",
  "Update client security diversity",
  "Update client security equity",
  "Update client security fairness",
  "Update client security justice",
  "Update client security ethics",
  "Update client security morality",
  "Update client security integrity",
  "Update client security honesty",
  "Update client security trustworthiness",
  "Update client security dependability",
  "Update client security consistency",
  "Update client security uniformity",
  "Update client security standardization",
  "Update client security normalization",
  "Update client security optimization",
  "Update client security improvement",
  "Update client security innovation",
  "Update client security creativity",
  "Update client security ingenuity",
  "Update client security inventiveness",
  "Update client security originality",
  "Update client security novelty",
  "Update client security uniqueness",
  "Update client security distinctiveness",
  "Update client security differentiation",
  "Update client security advantage",
  "Update client security benefit",
  "Update client security value",
  "Update client security worth",
  "Update client security merit",
  "Update client security significance",
  "Update client security importance",
  "Update client security relevance",
  "Update client security applicability",
  "Update client security suitability",
  "Update client security appropriateness",
  "Update client security adequacy",
  "Update client security sufficiency",
  "Update client security completeness",
  "Update client security thoroughness",
  "Update client security comprehensiveness",
  "Update client security exhaustiveness",
  "Update client security inclusiveness",
  "Update client security wholeness",
  "Update client security totality",
  "Update client security entirety",
  "Update client security fullness",
  "Update client security richness",
  "Update client security depth",
  "Update client security breadth",
  "Update client security width",
  "Update client security height",
  "Update client security length",
  "Update client security size",
  "Update client security scale",
  "Update client security magnitude",
  "Update client security extent",
  "Update client security degree",
  "Update client security level",
  "Update client security grade",
  "Update client security rank",
  "Update client security tier",
  "Update client security class",
  "Update client security category",
  "Update client security type",
  "Update client security kind",
  "Update client security sort",
  "Update client security variety",
  "Update client security form",
  "Update client security shape",
  "Update client security structure",
  "Update client security pattern",
  "Update client security design",
  "Update client security layout",
  "Update client security arrangement",
  "Update client security organization",
  "Update client security configuration",
  "Update client security setup",
  "Update client security installation",
  "Update client security deployment",
  "Update client security implementation",
  "Update client security execution",
  "Update client security operation",
  "Update client security running",
  "Update client security functioning",
  "Update client security working",
  "Update client security performance",
  "Update client security behavior",
  "Update client security conduct",
  "Update client security manner",
  "Update client security mode",
  "Update client security style",
  "Update client security method",
  "Update client security technique",
  "Update client security approach",
  "Update client security strategy",
  "Update client security tactic",
  "Update client security plan",
  "Update client security scheme",
  "Update client security program",
  "Update client security project",
  "Update client security initiative",
  "Update client security campaign",
  "Update client security drive",
  "Update client security push",
  "Update client security effort",
  "Update client security endeavor",
  "Update client security undertaking",
  "Update client security venture",
  "Update client security enterprise",
  "Update client security business",
  "Update client security company",
  "Update client security organization",
  "Update client security institution",
  "Update client security agency",
  "Update client security authority",
  "Update client security government",
  "Update client security state",
  "Update client security nation",
  "Update client security country",
  "Update client security region",
  "Update client security area",
  "Update client security zone",
  "Update client security district",
  "Update client security territory",
  "Update client security province",
  "Update client security state",
  "Update client security county",
  "Update client security city",
  "Update client security town",
  "Update client security village",
  "Update client security hamlet",
  "Update client security locality",
  "Update client security neighborhood",
  "Update client security community",
  "Update client security society",
  "Update client security population",
  "Update client security people",
  "Update client security citizens",
  "Update client security residents",
  "Update client security inhabitants",
  "Update client security occupants",
  "Update client security dwellers",
  "Update client security inhabitants",
  "Update client security populace",
  "Update client security public",
  "Update client security masses",
  "Update client security crowd",
  "Update client security audience",
  "Update client security viewers",
  "Update client security spectators",
  "Update client security observers",
  "Update client security witnesses",
  "Update client security onlookers",
  "Update client security bystanders",
  "Update client security passersby",
  "Update client security pedestrians",
  "Update client security walkers",
  "Update client security hikers",
  "Update client security trekkers",
  "Update client security travelers",
  "Update client security tourists",
  "Update client security visitors",
  "Update client security guests",
  "Update client security hosts",
  "Update client security owners",
  "Update client security managers",
  "Update client security directors",
  "Update client security executives",
  "Update client security leaders",
  "Update client security chiefs",
  "Update client security heads",
  "Update client security bosses",
  "Update client security supervisors",
  "Update client security controllers",
  "Update client security administrators",
  "Update client security operators",
  "Update client security technicians",
  "Update client security engineers",
  "Update client security developers",
  "Update client security programmers",
  "Update client security coders",
  "Update client security writers",
  "Update client security authors",
  "Update client security creators",
  "Update client security makers",
  "Update client security builders",
  "Update client security constructors",
  "Update client security architects",
  "Update client security designers",
  "Update client security planners",
  "Update client security strategists",
  "Update client security analysts",
  "Update client security researchers",
  "Update client security scientists",
  "Update client security experts",
  "Update client security specialists",
  "Update client security professionals",
  "Update client security practitioners",
  "Update client security consultants",
  "Update client security advisors",
  "Update client security counselors",
  "Update client security mentors",
  "Update client security coaches",
  "Update client security trainers",
  "Update client security teachers",
  "Update client security educators",
  "Update client security instructors",
  "Update client security professors",
  "Update client security lecturers",
  "Update client security scholars",
  "Update client security academics",
  "Update client security students",
  "Update client security learners",
  "Update client security pupils",
  "Update client security apprentices",
  "Update client security interns",
  "Update client security trainees",
  "Update client security novices",
  "Update client security beginners",
  "Update client security starters",
  "Update client security initiates",
  "Update client security newcomers",
  "Update client security entrants",
  "Update client security arrivals",
  "Update client security visitors",
  "Update client security guests",
  "Update client security customers",
  "Update client security clients",
  "Update client security patrons",
  "Update client security consumers",
  "Update client security users",
  "Update client security subscribers",
  "Update client security members",
  "Update client security participants",
  "Update client security contributors",
  "Update client security donors",
  "Update client security supporters",
  "Update client security backers",
  "Update client security sponsors",
  "Update client security partners",
  "Update client security allies",
  "Update client security friends",
  "Update client security associates",
  "Update client security colleagues",
  "Update client security peers",
  "Update client security mates",
  "Update client security companions",
  "Update client security partners",
  "Update client security teammates",
  "Update client security colleagues",
  "Update client security coworkers",
  "Update client security workmates",
  "Update client security fellow workers",
  "Update client security staff",
  "Update client security personnel",
  "Update client security workforce",
  "Update client security employees",
  "Update client security workers",
  "Update client security labor",
  "Update client security manpower",
  "Update client security human resources",
  "Update client security talent",
  "Update client security skills",
  "Update client security abilities",
  "Update client security capabilities",
  "Update client security competencies",
  "Update client security qualifications",
  "Update client security credentials",
  "Update client security certifications",
  "Update client security licenses",
  "Update client security permits",
  "Update client security authorizations",
  "Update client security permissions",
  "Update client security approvals",
  "Update client security consents",
  "Update client security agreements",
  "Update client security contracts",
  "Update client security deals",
  "Update client security arrangements",
  "Update client security understandings",
  "Update client security commitments",
  "Update client security obligations",
  "Update client security responsibilities",
  "Update client security duties",
  "Update client security tasks",
  "Update client security jobs",
  "Update client security roles",
  "Update client security positions",
  "Update client security functions",
  "Update client security assignments",
  "Update client security projects",
  "Update client security programs",
  "Update client security initiatives",
  "Update client security campaigns",
  "Update client security drives",
  "Update client security pushes",
  "Update client security efforts",
  "Update client security endeavors",
  "Update client security undertakings",
  "Update client security ventures",
  "Update client security enterprises",
  "Update client security businesses",
  "Update client security companies",
  "Update client security organizations",
  "Update client security institutions",
  "Update client security agencies",
  "Update client security authorities",
  "Update client security governments",
  "Update client security states",
  "Update client security nations",
  "Update client security countries",
  "Update client security regions",
  "Update client security areas",
  "Update client security zones",
  "Update client security districts",
  "Update client security territories",
  "Update client security provinces",
  "Update client security states",
  "Update client security counties",
  "Update client security cities",
  "Update client security towns",
  "Update client security villages",
  "Update client security hamlets",
  "Update client security localities",
  "Update client security neighborhoods",
  "Update client security communities",
  "Update client security societies",
  "Update client security populations",
  "Update client security people",
  "Update client security citizens",
  "Update client security residents",
  "Update client security inhabitants",
  "Update client security occupants",
  "Update client security dwellers",
  "Update client security inhabitants",
  "Update client security populace",
  "Update client security public",
  "Update client security masses",
  "Update client security crowd",
  "Update client security audience",
  "Update client security viewers",
  "Update client security spectators",
  "Update client security observers",
  "Update client security witnesses",
  "Update client security onlookers",
  "Update client security bystanders",
  "Update client security passersby",
  "Update client security pedestrians",
  "Update client security walkers",
  "Update client security hikers",
  "Update client security trekkers",
  "Update client security travelers",
  "Update client security tourists",
  "Update client security visitors",
  "Update client security guests",
  "Update client security hosts",
  "Update client security owners",
  "Update client security managers",
  "Update client security directors",
  "Update client security executives",
  "Update client security leaders",
  "Update client security chiefs",
  "Update client security heads",
  "Update client security bosses",
  "Update client security supervisors",
  "Update client security controllers",
  "Update client security administrators",
  "Update client security operators",
  "Update client security technicians",
  "Update client security engineers",
  "Update client security developers",
  "Update client security programmers",
  "Update client security coders",
  "Update client security writers",
  "Update client security authors",
  "Update client security creators",
  "Update client security makers",
  "Update client security builders",
  "Update client security constructors",
  "Update client security architects",
  "Update client security designers",
  "Update client security planners",
  "Update client security strategists",
  "Update client security analysts",
  "Update client security researchers",
  "Update client security scientists",
  "Update client security experts",
  "Update client security specialists",
  "Update client security professionals",
  "Update client security practitioners",
  "Update client security consultants",
  "Update client security advisors",
  "Update client security counselors",
  "Update client security mentors",
  "Update client security coaches",
  "Update client security trainers",
  "Update client security teachers",
  "Update client security educators",
  "Update client security instructors",
  "Update client security professors",
  "Update client security lecturers",
  "Update client security scholars",
  "Update client security academics",
  "Update client security students",
  "Update client security learners",
  "Update client security pupils",
  "Update client security apprentices",
  "Update client security interns",
  "Update client security trainees",
  "Update client security novices",
  "Update client security beginners",
  "Update client security starters",
  "Update client security initiates",
  "Update client security newcomers",
  "Update client security entrants",
  "Update client security arrivals",
  "Update client security visitors",
  "Update client security guests",
  "Update client security customers",
  "Update client security clients",
  "Update client security patrons",
  "Update client security consumers",
  "Update client security users",
  "Update client security subscribers",
  "Update client security members",
  "Update client security participants",
  "Update client security contributors",
  "Update client security donors",
  "Update client security supporters",
  "Update client security backers",
  "Update client security sponsors",
  "Update client security partners",
  "Update client security allies",
  "Update client security friends",
  "Update client security associates",
  "Update client security colleagues",
  "Update client security peers",
  "Update client security mates",
  "Update client security companions",
  "Update client security partners",
  "Update client security teammates",
  "Update client security colleagues",
  "Update client security coworkers",
  "Update client security workmates",
  "Update client security fellow workers",
  "Update client security staff",
  "Update client security personnel",
  "Update client security workforce",
  "Update client security employees",
  "Update client security workers",
  "Update client security labor",
  "Update client security manpower",
  "Update client security human resources",
  "Update client security talent",
  "Update client security skills",
  "Update client security abilities",
  "Update client security capabilities",
  "Update client security competencies",
  "Update client security qualifications",
  "Update client security credentials",
  "Update client security certifications",
  "Update client security licenses",
  "Update client security permits",
  "Update client security authorizations",
  "Update client security permissions",
  "Update client security approvals",
  "Update client security consents",
  "Update client security agreements",
  "Update client security contracts",
  "Update client security deals",
  "Update client security arrangements",
  "Update client security understandings",
  "Update client security commitments",
  "Update client security obligations",
  "Update client security responsibilities",
  "Update client security duties",
  "Update client security tasks",
  "Update client security jobs",
  "Update client security roles",
  "Update client security positions",
  "Update client security functions",
  "Update client security assignments",
  "Update client security projects",
  "Update client security programs",
  "Update client security initiatives",
  "Update client security campaigns",
  "Update client security drives",
  "Update client security pushes",
  "Update client security efforts",
  "Update client security endeavors",
  "Update client security undertakings",
  "Update client security ventures",
  "Update client security enterprises",
  "Update client security businesses",
  "Update client security companies",
  "Update client security organizations",
  "Update client security institutions",
  "Update client security agencies",
  "Update client security authorities",
  "Update client security governments",
  "Update client security states",
  "Update client security nations",
  "Update client security countries",
  "Update client security regions",
  "Update client security areas",
  "Update client security zones",
  "Update client security districts",
  "Update client security territories",
  "Update client security provinces",
  "Update client security states",
  "Update client security counties",
  "Update client security cities",
  "Update client security towns",
  "Update client security villages",
  "Update client security hamlets",
  "Update client security localities",
  "Update client security neighborhoods",
  "Update client security communities",
  "Update client security societies",
  "Update client security populations",
  "Update client security people",
  "Update client security citizens",
  "Update client security residents",
  "Update client security inhabitants",
  "Update client security occupants",
  "Update client security dwellers",
  "Update client security inhabitants",
  "Update client security populace",
  "Update client security public",
  "Update client security masses",
  "Update client security crowd",
  "Update client security audience",
  "Update client security viewers",
  "Update client security spectators",
  "Update client security observers",
  "Update client security witnesses",
  "Update client security onlookers",
  "Update client security bystanders",
  "Update client security passersby",
  "Update client security pedestrians",
  "Update client security walkers",
  "Update client security hikers",
  "Update client security trekkers",
  "Update client security travelers",
  "Update client security tourists",
  "Update client security visitors",
  "Update client security guests",
  "Update client security hosts",
  "Update client security owners",
  "Update client security managers",
  "Update client security directors",
  "Update client security executives",
  "Update client security leaders",
  "Update client security chiefs",
  "Update client security heads",
  "Update client security bosses",
  "Update client security supervisors",
  "Update client security controllers",
  "Update client security administrators",
  "Update client security operators",
  "Update client security technicians",
  "Update client security engineers",
  "Update client security developers",
  "Update client security programmers",
  "Update client security coders",
  "Update client security writers",
  "Update client security authors",
  "Update client security creators",
  "Update client security makers",
  "Update client security builders",
  "Update client security constructors",
  "Update client security architects",
  "Update client security designers",
  "Update client security planners",
  "Update client security strategists",
  "Update client security analysts",
  "Update client security researchers",
  "Update client security scientists",
  "Update client security experts",
  "Update client security specialists",
  "Update client security professionals",
  "Update client security practitioners",
  "Update client security consultants",
  "Update client security advisors",
  "Update client security counselors",
  "Update client security mentors",
  "Update client security coaches",
  "Update client security trainers",
  "Update client security teachers",
  "Update client security educators",
  "Update client security instructors",
  "Update client security professors",
  "Update client security lecturers",
  "Update client security scholars",
  "Update client security academics",
  "Update client security students",
  "Update client security learners",
  "Update client security pupils",
  "Update client security apprentices",
  "Update client security interns",
  "Update client security trainees",
  "Update client security novices",
  "Update client security beginners",
  "Update client security starters",
  "Update client security initiates",
  "Update client security newcomers",
  "Update client security entrants",
  "Update client security arrivals",
  "Update client security visitors",
  "Update client security guests",
  "Update client security customers",
  "Update client security clients",
  "Update client security patrons",
  "Update client security consumers",
  "Update client security users",
  "Update client security subscribers",
  "Update client security members",
  "Update client security participants",
  "Update client security contributors",
  "Update client security donors",
  "Update client security supporters",
  "Update client security backers",
  "Update client security sponsors",
  "Update client security partners",
  "Update client security allies",
  "Update client security friends",
  "Update client security associates",
  "Update client security colleagues",
  "Update client security peers",
  "Update client security mates",
  "Update client security companions",
  "Update client security partners",
  "Update client security teammates",
  "Update client security colleagues",
  "Update client security coworkers",
  "Update client security workmates",
  "Update client security fellow workers",
  "Update client security staff",
  "Update client security personnel",
  "Update client security workforce",
  "Update client security employees",
  "Update client security workers",
  "Update client security labor",
  "Update client security manpower",
  "Update client security human resources",
  "Update client security talent",
  "Update client security skills",
  "Update client security abilities",
  "Update client security capabilities",
  "Update client security competencies",
  "Update client security qualifications",
  "Update client security credentials",
  "Update client security certifications",
  "Update client security licenses",
  "Update client security permits",
  "Update client security authorizations",
  "Update client security permissions",
  "Update client security approvals",
  "Update client security consents",
  "Update client security agreements",
  "Update client security contracts",
  "Update client security deals",
  "Update client security arrangements",
  "Update client security understandings",
  "Update client security commitments",
  "Update client security obligations",
  "Update client security responsibilities",
  "Update client security duties",
  "Update client security tasks",
  "Update client security jobs",
  "Update client security roles",
  "Update client security positions",
  "Update client security functions",
  "Update client security assignments",
]

async function main() {
  console.log("Seeding 200 test tasks...")

  // Get existing clients and employees
  const clients = await prisma.client.findMany({ select: { id: true } })
  const employees = await prisma.employee.findMany({ 
    where: { isActive: true },
    select: { id: true } 
  })

  if (clients.length === 0) {
    console.error("No clients found. Please seed clients first.")
    process.exit(1)
  }

  if (employees.length === 0) {
    console.error("No employees found. Please seed employees first.")
    process.exit(1)
  }

  console.log(`Found ${clients.length} clients and ${employees.length} employees`)

  // Generate 200 tasks
  const tasks = []
  for (let i = 0; i < 200; i++) {
    const client = clients[Math.floor(Math.random() * clients.length)]
    const employee = employees[Math.floor(Math.random() * employees.length)]
    const status = TASK_STATUSES[Math.floor(Math.random() * TASK_STATUSES.length)]
    const priority = TASK_PRIORITIES[Math.floor(Math.random() * TASK_PRIORITIES.length)]
    const serviceType = SERVICE_TYPES[Math.floor(Math.random() * SERVICE_TYPES.length)]
    const title = TASK_TITLES[Math.floor(Math.random() * TASK_TITLES.length)]
    
    // Generate due date (between -30 days and +90 days from now)
    const dueDate = new Date()
    dueDate.setDate(dueDate.getDate() + Math.floor(Math.random() * 120) - 30)

    // Some tasks have completion date if status is FILED_DONE
    let completionDate = null
    if (status === "FILED_DONE" && Math.random() > 0.5) {
      completionDate = new Date(dueDate)
      completionDate.setDate(completionDate.getDate() - Math.floor(Math.random() * 7))
    }

    tasks.push({
      clientId: client.id,
      title: `${title} #${i + 1}`,
      description: `Test task ${i + 1} for QA testing purposes. This is a generated task to test the Work Tracker functionality.`,
      status,
      priority,
      serviceType,
      assignedEmployeeId: Math.random() > 0.2 ? employee.id : null, // 20% unassigned
      dueDate,
      completionDate,
      remarks: `QA test task ${i + 1}`,
      isOverdue: dueDate < new Date() && status !== "FILED_DONE",
    })
  }

  // Insert tasks in batches
  const batchSize = 50
  for (let i = 0; i < tasks.length; i += batchSize) {
    const batch = tasks.slice(i, i + batchSize)
    await prisma.task.createMany({ data: batch })
    console.log(`Inserted batch ${Math.floor(i / batchSize) + 1}/${Math.ceil(tasks.length / batchSize)}`)
  }

  console.log("Successfully seeded 200 test tasks!")
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
